apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo
spec:
  selector:
    matchLabels:
      app: hugo
  template:
    metadata:
      labels:
        app: hugo
    spec:
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.2
        env:
          - name: GIT_SYNC_REPO
            value: "https://github.com/sachiniyer/blog.git"
          - name: GIT_SYNC_BRANCH
            value: "main"
          - name: GIT_SYNC_ROOT
            value: /data
          - name: GIT_SYNC_DEST
            value: "hugo"
          - name: GIT_SYNC_MAX_FAILURES
            value: "-1"
          - name: GIT_SYNC_DEPTH
            value: "1"
          - name: GIT_SYNC_SUBMODULES
            value: "recursive"
        securityContext:
          runAsUser: 65533 # git-sync user
        volumeMounts:
        - name: git-checkout
          mountPath: /data
          readOnly: false
      - name: hugo
        env:
          - name: HUGO_VERSION
            value: 0.111.3
          - name: BASE_URL
            value: https://blog.sachiniyer.com
          - name: ENVIRONMENT
            value: live
        image: debian
        args:
          - sh
          - -c
          - >
            apt update;
            apt install wget -y;
            cd /tmp;
            wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz;
            tar zxvf hugo_${HUGO_VERSION}_linux-amd64.tar.gz;
            cd /data;
            /tmp/hugo server -s hugo --appendPort=false -e $ENVIRONMENT --bind 0.0.0.0 --baseURL $BASE_URL --buildDrafts
        volumeMounts:
        - name: git-checkout
          mountPath: /data
          readOnly: false

      volumes:
      - name: git-checkout
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hugo-service
spec:
  ports:
    - name: web
      port: 1313
      protocol: TCP
  selector:
    app: hugo
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-cert
  namespace: blog
spec:
  commonName: blog.sachiniyer.com
  secretName: blog-cert
  dnsNames:
    - blog.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: blog-ingress
spec:
  tls:
  - secretName: blog-cert
  rules:
  - host: blog.sachiniyer.com
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: hugo-service
             port:
               number: 1313
