#!/bin/sh
wget -q "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz"
tar zxvf hugo_"${HUGO_VERSION}_linux-amd64.tar.gz"

echo "./hugo server -s $DIR -e $ENVIRONMENT --bind 0.0.0.0 --baseURL $BASE_URL -p $PORT --disableFastRender --appendPort=false"

./hugo server -s "$DIR" -e "$ENVIRONMENT" --bind 0.0.0.0 --baseURL "$BASE_URL" -p "$PORT" --disableFastRender --appendPort=false
